<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-23 at 20:18:32.
 */
class CalculadoraTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Calculadora
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Calculadora;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Calculadora::soma
     * @todo   Implement testSoma().
     */
    public function testSomaNulo()
    {
        $this->assertEquals(null, $this->object->soma(3, 1));
    }
    
    public function testSomaReal(){
        $this->assertEquals(2,$this->object->soma(1, 1));
    }
}
