<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-23 at 20:27:36.
 */
class PessoaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Pessoa
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Pessoa;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Pessoa::excluir
     * @todo   Implement testExcluir().
     */
    public function testExcluir() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->excluir());
    }

    /**
     * @covers Pessoa::renovar
     * @todo   Implement testRenovar().
     */
    public function testRenovar() {
        // Remove the following lines when you implement this test.
        $this->assertNotNull($this->object->renovar(0, 0));
    }

}
